service: ${env:SERVICE}

frameworkVersion: "3"

provider:
  name: aws
  deploymentMethod: direct
  # REF: https://www.serverless.com/blog/container-support-for-lambda
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./
        file: Dockerfile
        buildArgs:
          MODEL: ${env:MODEL}
  stage: dev
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"

functions:
  embeddings:
    image:
      name: appimage
    memorySize: ${env:MEMORY_SIZE}
    environment:
      MODEL: ${env:MODEL}
      NORMALIZE_EMBEDDINGS: ${env:NORMALIZE_EMBEDDINGS}
      VERBOSE: ${env:VERBOSE}
      HF_HOME: /tmp/hf_home
    timeout: 900
    # https://www.serverless.com/framework/docs/providers/aws/guide/functions#lambda-function-urls
    url: true
